---
- hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Listar S3 Bucket
      aws_s3:
        bucket: "{{ bucket_name }}"
        mode: list
       
    - name: Add CA to service
      uri:
        url: "{{ manageiq.api_url }}/api/{{ manageiq.service/custom_attributes }}"
        method: POST
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type:  application/json
        body_format: json
        body:
          action: add
          resource:
            resources:
              name: "Nombre Bucket S3"
                value: "{{ bucket_name }}"
              name: "Otro Campo"
                value: "Otro valor"
               
