---
- hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Crear S3 Bucket
      block:
        -  aws_s3:
             bucket: "{{ bucket_name }}"
             mode: create
             permission: "{{ bucket_permission }}"
             region: ca-central-1
             notify: Create and attach DRO + Add Custom Attributes and assing TAGs to service  
             register: create_bucket_reg
      rescue:
        - debug: 
            msg: "El resultado del registro es: {{ create_bucket_reg.stdout }}"
        - debug: 
            msg: "El resultado del ansible_failed_result: {{ ansible_failed_result.stdout }}"   
  
  handlers:
    - name: Create DRO entry for AWS S3
      uri:
        url: "{{ manageiq.api_url }}/api/generic_objects"
        method: POST
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type:  application/json
        body_format: json
        body:
          action: create
          name: "{{ bucket_name }}"
          generic_object_definition:
            href: "{{ manageiq.api_url }}/api/generic_object_definitions/99000000000001"
          property_attributes:
            dro_bucket_name: "{{ bucket_name }}"
            dro_bucket_permission: "{{ bucket_permission }}"
            #dro_bucket_keys: "{{ bucket_keys }}"
          associations:
            service:
            - href: "{{ manageiq.api_url }}/api/{{ manageiq.service }}"
      register: dro
      listen: "Create and attach DRO + Add Custom Attributes and assing TAGs to service"
           
    - name: Add DRO to service
      uri:
        url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}"
        method: POST
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type:  application/json
        body_format: json
        body:
          action: add_resource
          resource:
            resource:
              href: "{{ dro.json.results[0].href }}"    
      listen: "Create and attach DRO + Add Custom Attributes and assing TAGs to service"
     
    - name: Add TAGs to S3
      uri:
        url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}/tags"
        method: POST
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type:  application/json
        body_format: json
        body:
          action: assign
          resources:
            - category: "senha_ambiente"
              name: "senha_ambiente_desarrollo"
            - category: "senha_nube"
              name: "senha_publica_aws"
            - category: "senha_almacenamiento"
              name: "senha_almacenamiento_s3"
      listen: "Create and attach DRO + Add Custom Attributes and assing TAGs to service"
     
    - name: Add Custom Attributes to S3
      uri:
        url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}/custom_attributes"
        method: POST
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type:  application/json
        body_format: json
        body:
          action: add
          resources:
            - name: "Work Order"
              value: "{{ numero_de_ticket  }}"
            - name: "General"
              #value: "{{ nombre_general  }}"
              value: "General 01"
            - name: "Central"
              #value: "{{ nombre_central  }}"
              value: "Central 01"
            - name: "Aplicación"
              #value: "{{ nombre_aplicacion }}"
              value: "App S3"
            - name: "Versión"
              #value: "{{ version_proyecto }}"
              value: "1.0"
      listen: "Create and attach DRO + Add Custom Attributes and assing TAGs to service"
