---
- hosts: localhost
  gather_facts: False
  connection: local    
  tasks:
    - name: Listar todos los S3 Bucket
      aws_s3_bucket_facts:
        #ec2_url: some_aws_region
        #aws_access_key: some_key
        #aws_secret_key: some_secret_key
        validate_certs: no
        region: ca-central-1
