---
- hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Crear S3 Bucket
      aws_s3:
        #ignore_nonexistent_bucket: True
        bucket: "{{ bucket_name }}"
        mode: create
        permission: "{{ bucket_permission }}"
        region: ca-central-1
      notify: Create and attach DRO to service
        
  handlers:
    - name: Create DRO entry for AWS S3
      uri:
        url: "{{ manageiq.api_url }}/api/generic_objects"
        method: POST
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type:  application/json
        body_format: json
        body:
          action: create
          name: "{{ bucket_name }}"
          generic_object_definition:
            href: "{{ manageiq.api_url }}/api/generic_object_definitions/1000000000001"
          property_attributes:
            dro_bucket_name: "{{ bucket_name }}"
            dro_bucket_permission: "{{ bucket_permission }}"
            #dro_bucket_keys: "{{ bucket_keys }}"
          associations:
            service:
            #- href: "{{ service.json.resources|last|json_query('href') }}"
            - href: "{{ manageiq.api_url }}/api/{{ manageiq.service }}"
      register: dro
      listen: "Create and attach DRO to service"
           
    - name: Add DRO to service
      uri:
        #url: "{{ service.json.resources|last|json_query('href') }}"
        url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}"
        method: POST
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type:  application/json
        body_format: json
        body:
          action: add_resource
          resource:
            resource:
              href: "{{ dro.json.results[0].href }}"    
      listen: "Create and attach DRO to service"
