---
- hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Add TAGs to service
      uri:
        url: https://192.168.122.146/api/services/99000000000072/tags
        method: POST
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type:  application/json
        body_format: json
        body:
          action: assign
          resources:
            - name: "Storage Mapping"
              value: "Storage 1"
