---
- hosts: all
  gather_facts: False
  #connection: local
  tasks:
    - name: Generar contraseña/semilla adminsenha
      shell: date | sha256sum | base64 | head -c 16
      register: contra_sem
      no_log: true
      #listen: "Generar usuarios y comunicar passwords"
  
    - name: Genera el hash de adminsenha
      shell: openssl passwd -1 -salt "{{ contra_sem.stdout }}" "{{ contra_sem.stdout }}"
      register: usu_contra
      no_log: true
      
    - debug:
        msg: "La contraseña es de adminsenha es: {{ contra_sem.stdout }} y el hash: {{ usu_contra.stdout }}"
        
    - name: Genera usuario 'adminsenha' y se agrega a grupo wheel
      user:
        name: adminsenha
        shell: /bin/bash
        groups: wheel
        append: yes
        password: "{{ usu_contra.stdout }}"
        update_password: always
      register: genusu_adminsenha
      when: ansible_distribution == "Red Hat Enterprise Linux"
      #listen: "Generar usuarios y comunicar passwords"
      
    - name: Generar contraseña/semilla root
      shell: date | sha256sum | base64 | head -c 16
      register: contraroot_sem
      no_log: true
      #listen: "Generar usuarios y comunicar passwords"
  
    - name: Genera el hash de root
      shell: openssl passwd -1 -salt "{{ contraroot_sem.stdout }}" "{{ contraroot_sem.stdout }}"
      register: usuroot_contra
      no_log: true
      
    - debug:
        msg: "La contraseña es de root es: {{ contraroot_sem.stdout }} y el hash: {{ usuroot_contra.stdout }}"
        
    - name: "Modificación de contraseña root"
      user:
        name: root
        password: "{{ usuroot_contra.stdout }}"
        update_password: always
      register: modusu_root
      
