---
- hosts: all
  gather_facts: False
  #connection: local
  tasks:
    - name: Genera contraseña/semilla adminsenha
      shell: date | sha256sum | base64 | head -c 16
      register: contraadminsenha_sem
      #no_log: true
        
    - name: OS RHEL
      shell: grep "Red Hat" /etc/*release
      register: rhel_os
      ignore_errors: yes
      
    - name: OS Oracle
      shell: grep "Oracle" /etc/*release
      register: oel_os
      ignore_errors: yes
      
    - name: Genera el hash de adminsenha
      shell: openssl passwd -1 -salt "{{ contraadminsenha_sem.stdout }}" "{{ contraadminsenha_sem.stdout }}"
      register: usu_contra
      when: contraadminsenha_sem.rc == 0
      #no_log: true

    - name: Genera usuario 'adminsenha' y se agrega a grupo wheel
      user:
        name: adminsenha
        shell: /bin/bash
        groups: wheel
        append: yes
        password: "{{ usu_contra.stdout }}"
        update_password: always
      register: genusu_adminsenha
      when: rhel_os.rc == 0 or oel_os.rc == 0 and usu_contra.rc == 0
            
    - name: Genera contraseña/semilla root
      shell: date | sha256sum | base64 | head -c 16
      register: contraroot_sem
      #no_log: true
        
    - name: Genera el hash de root
      shell: openssl passwd -1 -salt "{{ contraroot_sem.stdout }}" "{{ contraroot_sem.stdout }}"
      register: usuroot_contra
      when: contraroot_sem.rc == 0
      #no_log: true
      
    - debug:
        msg: "La contraseña es de root es: {{ contraroot_sem.stdout }} y el hash: {{ usuroot_contra.stdout }}"
        
    - name: Modifica contraseña root
      user:
        name: root
        password: "{{ usuroot_contra.stdout }}"
        update_password: always
      register: modusu_root
      when: rhel_os.rc == 0 or oel_os.rc == 0 and usuroot_contra.rc == 0

    - name: Notifica contraseña adminsenha base64
      shell: echo "{{ contraadminsenha_sem.stdout }}" | base64
      register: notificaadminsenha_contra
      when: genusu_adminsenha.failed == "False"
      #ignore_errors: yes
      #no_log: true
      
    - name: Notifica contraseña root base64
      shell: echo "{{ contraroot_sem.stdout }}" | base64
      register: notificaroot_contra
      when: modusu_root.failed == "False"
      #ignore_errors: yes
      #no_log: true
      
    - debug:
        msg: "La contraseña base64 de root es: {{ notificaroot_contra.stdout }}"
        
    - debug:
        msg: "La salida de genusu_adminsenha es: {{ genusu_adminsenha }}"
        
    - debug:
        msg: "La salida de modusu_root es: {{ modusu_root }}"
         
    - name: Estado de la generación y notificación de usuarios/contraseñas
      debug:
        msg: "Los usuarios y contraseñas se generaron y notificaron de manera exitosa"
      when: notificaadminsenha_contra.rc == 0 and notificaroot_contra.rc == 0     
      #ignore_errors: yes
# Se envían por mail en las notificaciones los passwords con las variables notificaadminsenha_contra.stdout y notificaroot_contra.stdout
