---
- hosts: 192.168.122.38
  gather_facts: False
#  connection: local
  tasks:
    - name: Add the user 'adminsenha' with a bash shell, appending the group 'whell'
      shell: date | sha256sum | base64 | head -c 16
      register: user_pass
      no_log: true
      #listen: "Create, change and notify users"
      
    - debug:
        msg: El password es {{ user_pass.stdout }}
        
    - name: Add the user 'adminsenha' with a bash shell, appending the group 'whell'
      user:
        name: adminsenha
        shell: /bin/bash
        groups: wheel
        append: yes
        password: {{ user_pass.stdout }}
        update_password: always
      #register: adduser_adminsenha
      #listen: "Create, change and notify users"
