---
- hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Crear S3 Bucket
      block:
        -  aws_s3:
             bucket: "{{ bucket_name }}"
             mode: create
             permission: "{{ bucket_permission }}"
             region: ca-central-1
           notify: Create and attach DRO + Add Custom Attributes and assing TAGs to service  
           register: create_bucket_reg
      rescue:
        - debug: 
            var: "{{ create_bucket_reg }}"
        #- debug: 
            #msg: "El resultado del ansible_failed_result: {{ ansible_failed_result }}"   
  
  handlers:
    - name: Create DRO entry for AWS S3
      uri:
        url: "{{ manageiq.api_url }}/api/generic_objects"
        method: POST
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type:  application/json
        body_format: json
        body:
          action: create
          name: "{{ bucket_name }}"
          generic_object_definition:
            href: "{{ manageiq.api_url }}/api/generic_object_definitions/99000000000001"
          property_attributes:
            dro_bucket_name: "{{ bucket_name }}"
            dro_bucket_permission: "{{ bucket_permission }}"
            #dro_bucket_keys: "{{ bucket_keys }}"
          associations:
            service:
            - href: "{{ manageiq.api_url }}/api/{{ manageiq.service }}"
      register: dro
      listen: "Create and attach DRO + Add Custom Attributes and assing TAGs to service"
