---
- hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: AWS900-00 Validación de existencia de Bucket
      aws_s3:
        bucket: "{{ bucket_name }}"
        mode: list
      ignore_errors: true
      register: valida_bucket_reg
     
    - block:
        - name: AWS900-01 Colectar error
          shell: echo "Error tarea AWS900-00: {{ valida_bucket_reg.msg }}" >> /tmp/some_file.error
        - name: AWS900-02 Salir por fallo al validar bucket
          fail:
            msg: "El nombre de bucket ingresado ya existe, intente con otro nombre" 
      when: valida_bucket_reg is succeeded 
    
    - name: AWS901-00 Crear bucket S3
      aws_s3: 
        bucket: "{{ bucket_name }}"
        mode: create
        permission: "{{ bucket_permission }}"
        region: ca-central-1
      ignore_errors: true
      register: crear_bucket_reg
      when: valida_bucket_reg is failed
  
    - block:
        - name: AWS901-01 Colectar error
          shell: echo "Error tarea AWS901-00: {{ crear_bucket_reg.msg }}" >> /tmp/some_file.error
        - name: AWS901-02 Salir por fallo al crear bucket
          fail:
            msg: "Error al crear bucket" 
      when: crear_bucket_reg is failed 
  
    - name: AWS902-00 Crear DRO para bucket S3
      uri:
        url: "{{ manageiq.api_url }}/api/generic_objects"
        method: POST
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type:  application/json
        body_format: json
        body:
          action: create
          name: "{{ bucket_name }}"
          generic_object_definition:
            href: "{{ manageiq.api_url }}/api/generic_object_definitions/99000000000001"
          property_attributes:
            dro_bucket_name: "{{ bucket_name }}"
            dro_bucket_permission: "{{ bucket_permission }}"
            #dro_bucket_keys: "{{ bucket_keys }}"
          associations:
            service:
            - href: "{{ manageiq.api_url }}/api/{{ manageiq.service }}"
      register: crear_dro_reg
      ignore_errors: true
      when: crear_bucket_reg is succeeded
      
    - block:
        - name: AWS902-01 Colectar error
          shell: echo "Error tarea AWS902-00: {{ crear_dro_reg.msg }}" >> /tmp/some_file.error
        - name: AWS902-02 Fallo al crear DRO
          debug:
            msg: "Error al crear DRO" 
      when: crear_dro_reg is failed 
     
    - name: AWS903-00 Agregar DRO al servicio
      uri:
        url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}"
        method: POST
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type:  application/json
        body_format: json
        body:
          action: add_resource
          resource:
            resource:
              href: "{{ dro.json.results[0].href }}"    
      register: agregar_dro_reg
      ignore_errors: true
      when: crear_dro_reg is succeeded
      
    - block:
        - name: AWS903-01 Colectar error
          shell: echo "Error tarea AWS903-00: {{ agregar_dro_reg.msg }}" >> /tmp/some_file.error
        - name: AWS903-02 Fallo al agregar DRO
          debug:
            msg: "Error al agregar DRO al servicio" 
      when: agregar_dro_reg is failed 
     
    - name: AWS904-00 Agregar TAGs de S3
      uri:
        url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}/tags"
        method: POST
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type:  application/json
        body_format: json
        body:
          action: assign
          resources:
            - category: "senha_ambiente"
              name: "senha_ambiente_desarrollo"
            - category: "senha_nube"
              name: "senha_publica_aws"
            - category: "senha_almacenamiento"
              name: "senha_almacenamiento_s3"
      ignore_errors: true
      register: agregar_tags_reg
      when: crear_bucket_reg is succeeded
      
    - block:
        - name: AWS904-01 Colectar error
          shell: echo "Error tarea AWS904-00: {{ agregar_tags_reg.msg }}" >> /tmp/some_file.error
        - name: AWS904-02 Fallo al agregar TAGs
          debug:
            msg: "Error al agregar TAGs al servicio" 
      when: agregar_tags_reg is failed 
     
    - name: AWS905-00 Agregar Custom Attributes a servicio
      uri:
        url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}/custom_attributes"
        method: POST
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type:  application/json
        body_format: json
        body:
          action: add
          resources:
            - name: "Work Order"
              #value: "{{ numero_de_ticket  }}"
              value: "REQS00000000001"
            - name: "General"
              #value: "{{ nombre_general  }}"
              value: "General 01"
            - name: "Central"
              #value: "{{ nombre_central  }}"
              value: "Central 01"
            - name: "Aplicación"
              #value: "{{ nombre_aplicacion }}"
              value: "App S3"
            - name: "Versión"
              #value: "{{ version_proyecto }}"
              value: "1.0"
      ignore_errors: true
      register: agregar_cu_reg
      when: crear_bucket_reg is succeeded
      
    - block:
        - name: AWS905-01 Colectar error
          shell: echo "Error tarea AWS905-00: {{ agregar_cu_reg.msg }}" >> /tmp/some_file.error
        - name: AWS905-02 Fallo al agregar CU
          debug:
            msg: "Error al agregar CU al servicio" 
      when: agregar_cu_reg is failed 
