
---
- hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: "Tarea ejemplo"
      # Ejemplo
      notify: Assing TAGs to service
        
  handlers:
    - name: Add TAGs to service
      uri:
        url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}/tags"
        method: POST
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type:  application/json
        body_format: json
        body:
          action: assign
          resources:
            - category: "senha_ambiente"
              name: "senha_ambiente_desarrollo"
            - category: "senha_nube"
              name: "senha_privada_vmware"
            - category: "senha_arq_mat"
              name: "senha_mat_rhel7"
      listen: "Assing TAGs to service"
