---
- hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: AWS900-00 Validación de existencia de Bucket
      aws_s3:
        bucket: "{{ bucket_name }}"
        mode: list
        region: ca-central-1
      ignore_errors: true
      register: valida_bucket_reg
     
    - debug:
        msg: "{{ valida_bucket_reg }}"
    
    - name: AWS901-00 Crear bucket S3
      aws_s3: 
        bucket: "{{ bucket_name }}"
        mode: create
        permission: "{{ bucket_permission }}"
        region: ca-central-1
      ignore_errors: true
      register: crear_bucket_reg
      notify: Create and attach DRO + Add Custom Attributes and assing TAGs to service
  
    - debug:
        msg: "{{ crear_bucket_reg }}"
  
    - name: AWS902-00 Crear DRO para bucket S3
      uri:
        url: "{{ manageiq.api_url }}/api/generic_objects"
        method: POST
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type:  application/json
        body_format: json
        body:
          action: create
          name: "{{ bucket_name }}"
          generic_object_definition:
            href: "{{ manageiq.api_url }}/api/generic_object_definitions/99000000000001"
          property_attributes:
            dro_bucket_name: "{{ bucket_name }}"
            dro_bucket_permission: "{{ bucket_permission }}"
            #dro_bucket_keys: "{{ bucket_keys }}"
          associations:
            service:
            - href: "{{ manageiq.api_url }}/api/{{ manageiq.service }}"
      register: crear_dro_reg
      ignore_errors: true
      
    - debug:
        msg: "{{ crear_dro_reg }}"
     
    - name: AWS903-00 Agregar DRO al servicio
      uri:
        url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}"
        method: POST
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type:  application/json
        body_format: json
        body:
          action: add_resource
          resource:
            resource:
              href: "{{ dro.json.results[0].href }}"    
      register: agregar_dro_reg
      ignore_errors: true
      when: crear_dro_reg is succeeded
      
    - debug:
        msg: "{{ agregar_dro_reg }}"
        
    - name: AWS904-00 Agregar TAGs de S3
      uri:
        url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}/tags"
        method: POST
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type:  application/json
        body_format: json
        body:
          action: assign
          resources:
            - category: "senha_ambiente"
              name: "senha_ambiente_desarrollo"
            - category: "senha_nube"
              name: "senha_publica_aws"
            - category: "senha_almacenamiento"
              name: "senha_almacenamiento_s3"
      ignore_errors: true
      register: agregar_tags_reg
      
    - debug:
        msg: "{{ agregar_tags_reg }}"
     
    - name: AWS905-00 Agregar Custom Attributes a servicio
      uri:
        url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}/custom_attributes"
        method: POST
        validate_certs: no
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type:  application/json
        body_format: json
        body:
          action: add
          resources:
            - name: "Work Order"
              #value: "{{ numero_de_ticket  }}"
              value: "REQS00000000001"
            - name: "General"
              #value: "{{ nombre_general  }}"
              value: "General 01"
            - name: "Central"
              #value: "{{ nombre_central  }}"
              value: "Central 01"
            - name: "Aplicación"
              #value: "{{ nombre_aplicacion }}"
              value: "App S3"
            - name: "Versión"
              #value: "{{ version_proyecto }}"
              value: "1.0"
      ignore_errors: true
      register: agregar_cu_reg
      
    - debug:
        msg: "{{ agregar_cu_reg }}"
