---
- hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Crear S3 Bucket
      aws_s3:
        ignore_nonexistent_bucket: True
        bucket: "{{ bucket_name }}"
        mode: create
        permission: "{{ bucket_permission }}"
      register: bucket_creation
      
    - debug:
        msg: "El DRO {{ bucket_name }} se creara exitosamente."
      register: dro
      when: bucket_creation
